#Enterprises#
INSERT INTO `enterprises`(`id`, `name`, `contract`) VALUES (NULL,'Tecnología Aplicada a Negocios S.A de C.V','713-UTIC-LPN-001-22');
INSERT INTO `enterprises`(`id`, `name`, `contract`) VALUES (NULL,'SecretarÍa de Infraestructura, Comunicaciones y Transportes','UTIC');

#Levels#
INSERT INTO `levels`(`id`, `type`) VALUES (NULL,'Escritura');
INSERT INTO `levels`(`id`, `type`) VALUES (NULL,'Lectura');
INSERT INTO `levels`(`id`, `type`) VALUES (NULL,'Escritura y Lectura');

INSERT INTO `locations`(`id`, `ubicacion`, `cubiculo`) VALUES (NULL,'Av. Insurgentes Sur 1089, Col. Nochebuena, Benito Juárez, 3720, CDMX,  UTIC Piso 9, Cubiculo 5','5');
INSERT INTO `locations`(`id`, `ubicacion`, `cubiculo`) VALUES (NULL,'Av. Insurgentes Sur 1089, Col. Nochebuena, Benito Juárez, 3720, CDMX,  UTIC Piso 9, Cubiculo 6','6');
INSERT INTO `locations`(`id`, `ubicacion`, `cubiculo`) VALUES (NULL,'Av. Insurgentes Sur 1089, Col. Nochebuena, Benito Juárez, 3720, CDMX,  UTIC Piso 9, Cubiculo 15','15');
INSERT INTO `locations`(`id`, `ubicacion`, `cubiculo`) VALUES (NULL,'Remoto',NULL);

#Rol#
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Administrador de Contrato');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Administrador del Servicio');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Administrador de Proyectos');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Analista de Software');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Arquitecto de Base de Datos');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Arquitecto de Software');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Controller Manager (Personal de apoyo)');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Coordinador de la mesa de servicio');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Desarrollador Cliente-Servidor');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Desarrollador Web');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Desarrollador Móvil');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Director Coordinador de Innovación y Desarrollo Tecnológico');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Director de Desarrollo Tecnológico');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Documentador');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Especialista en Metodología COSMIC');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Especialista en Seguridad Informática');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Ingeniero de pruebas');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Lider de proyecto');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Scrum Master');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Subdirector de Sistemas Administrativos');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Subdirector de Adminsitración de Portales');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'UI/UX');

#databases
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(1, 'SICCA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(2, 'INGPBA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(3, 'SITFYM', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(4, 'SIAC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(5, 'SIGTIC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(6, 'SIAFFA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(7, 'INGREP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(8, 'CONTRATO', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(9, 'UAC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(10, 'SIAFINT', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(11, 'SIAFREP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50004');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(12, 'SIAFNW', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(13, 'SUAJ', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(14, 'AGADOS', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(15, 'ADMSEG', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(16, 'MEDELIC2', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(17, 'SIGESPO', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(18, 'BI_SCT', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(19, 'SIGESYS', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(20, 'SIAFINP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(21, 'SIAFINFA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(22, 'ADMPBA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(23, 'DNC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(24, 'INGDES', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(25, 'SIEDGP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(26, 'ADMSEG2', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(27, 'CIS', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(28, 'CISREP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(29, 'MEDPREVD', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50014');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(30, 'ADVDB', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50016');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(31, 'IIE', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50016');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(32, 'ADMSEG', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(33, 'SIAF', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(34, 'ING', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(35, 'SIAC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(36, 'MEDPREVD', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(37, 'LICENCIA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(38, 'SIAFINT', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(39, 'SIGTIC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50004');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(40, 'SUAJ', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(41, 'SIAFINP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(42, 'CIS', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(43, 'DNC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(44, 'TFADMSEG', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(45, 'TFCIS', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(46, 'TFLFD', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(47, 'SITFYM', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50016');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(48, 'SUI_LFD', '', 'PostgreSQL', 'CentOS 7.7', 'Bajo', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(49, 'TIMBRADO SCT', '', 'PostgreSQL', 'CentOS 7.4', 'Bajo', 3, 'QA', '10.33.146.20', '5432');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(50, 'TIMBRADO AFAC', '', 'PostgreSQL', 'CentOS 7.4', 'Bajo', 3, 'QA', '10.38.10.20', '5432');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(51, 'JIRA', '', 'PostgreSQL', 'Ubuntu 18.04', 'Bajo', 3, 'QA', '10.38.239.37', '5432');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(52, 'GITLAB', '', 'PostgreSQL', 'RedHat 7.9', 'Bajo', 3, 'QA', '10.33.146.22', '5432');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(53, 'SUAJ', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.11.11', '5432');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(54, 'RECO', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5440');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(55, 'RNSAOP', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5440');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(56, 'ADMSEG_SVC', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5440');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(57, 'REGAUDIT', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5440');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(58, 'CABMUN', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5444');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(59, 'C_RURALES_BACK', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5444');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(60, 'C_RURALES_SEPOMEX', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5444');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(61, 'VUELA_SEGURO', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5446');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(62, 'CAT_RENAPO', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5448');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(63, 'RSIE', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5448');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(64, 'RSIPUMEX', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5448');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(65, 'siarmx', '', 'MySQL', 'CentOS 6.3', 'Bajo', 3, 'QA', '10.38.241.28', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(66, 'cass', '', 'MySQL', 'CentOS 6.3', 'Bajo', 3, 'QA', '10.38.241.28', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(67, 'banco_digital', '', 'MySQL', 'CentOS 6.3', 'Bajo', 3, 'QA', '10.38.241.28', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(68, 'glpi_sct', '', 'MySQL', 'Ubuntu 18.04', 'Bajo', 3, 'QA', '10.38.239.36', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(69, 'joomla_db', '', 'MySQL', 'RedHat 8.6', 'Bajo', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(70, 'sfv_portal', '', 'MySQL', 'RedHat 8.4', 'Bajo', 3, 'QA', '10.38.239.39', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(71, 'sfv_acceso', '', 'MySQL', 'RedHat 8.4', 'Bajo', 3, 'QA', '10.38.239.39', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(72, 'sintqa_portal', '', 'MySQL', 'RedHat 8.4', 'Bajo', 3, 'QA', '10.38.241.25', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(73, 'pdn_portal', '', 'MySQL', 'RedHat 8.5', 'Bajo', 3, 'QA', '10.38.240.29', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(74, 'repo_portal', '', 'MySQL', 'RedHat 8.5', 'Bajo', 3, 'QA', '10.38.240.29', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(75, 'Pegasus', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(76, 'Pegasus_110821', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(77, 'Pegasus_Consulta', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(78, 'Pegasus_Contenido', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(79, 'Pegasus_Contenido_2', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(80, 'Pegasus_Contenido_6', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(81, 'Pegasus_SSIS', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(82, 'PegasusV10', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(83, 'Pegasusv8', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(84, 'Pegasus_clon', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(85, 'Pegasus_SSIS', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.12', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(86, 'ReportServer', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.12', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(87, 'ReportServerTempDB', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.12', '');
