#Enterprises#
INSERT INTO `enterprises`(`id`, `name`, `contract`) VALUES (NULL,'Tecnología Aplicada a Negocios S.A de C.V','713-UTIC-LPN-001-22');
INSERT INTO `enterprises`(`id`, `name`, `contract`) VALUES (NULL,'SecretarÍa de Infraestructura, Comunicaciones y Transportes','UTIC');

#Levels#
INSERT INTO `levels`(`id`, `type`) VALUES (NULL,'Escritura');
INSERT INTO `levels`(`id`, `type`) VALUES (NULL,'Lectura');
INSERT INTO `levels`(`id`, `type`) VALUES (NULL,'Escritura y Lectura');

INSERT INTO `locations`(`id`, `ubicacion`, `cubiculo`) VALUES (NULL,'Av. Insurgentes Sur 1089, Col. Nochebuena, Benito Juárez, 3720, CDMX,  UTIC Piso 9, Cubiculo 5','5');
INSERT INTO `locations`(`id`, `ubicacion`, `cubiculo`) VALUES (NULL,'Av. Insurgentes Sur 1089, Col. Nochebuena, Benito Juárez, 3720, CDMX,  UTIC Piso 9, Cubiculo 6','6');
INSERT INTO `locations`(`id`, `ubicacion`, `cubiculo`) VALUES (NULL,'Av. Insurgentes Sur 1089, Col. Nochebuena, Benito Juárez, 3720, CDMX,  UTIC Piso 9, Cubiculo 15','15');
INSERT INTO `locations`(`id`, `ubicacion`, `cubiculo`) VALUES (NULL,'Remoto',NULL);

#Rol#
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Administrador de Contrato');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Administrador del Servicio');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Administrador de Proyectos');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Analista de Software');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Arquitecto de Base de Datos');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Arquitecto de Software');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Controller Manager (Personal de apoyo)');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Coordinador de la mesa de servicio');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Desarrollador Cliente-Servidor');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Desarrollador Web');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Desarrollador Móvil');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Director Coordinador de Innovación y Desarrollo Tecnológico');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Director de Desarrollo Tecnológico');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Documentador');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Especialista en Metodología COSMIC');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Especialista en Seguridad Informática');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Ingeniero de pruebas');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Lider de proyecto');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Scrum Master');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Subdirector de Sistemas Administrativos');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Subdirector de Adminsitración de Portales');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Subdirector de Innovación Tecnológica');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'Subdirector de Implementación y Administración de Aplicaciones');
INSERT INTO `rols`(`id`, `rol`) VALUES (NULL, 'UI/UX');

#databases
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SICCA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'INGPBA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SITFYM', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIGTIC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAFFA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'INGREP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'CONTRATO', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'UAC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAFINT', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAFREP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50004');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAFNW', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SUAJ', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'AGADOS', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'ADMSEG', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'MEDELIC2', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIGESPO', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'BI_SCT', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIGESYS', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAFINP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAFINFA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'ADMPBA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'DNC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'INGDES', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIEDGP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'ADMSEG2', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'CIS', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'CISREP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'MEDPREVD', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50014');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'ADVDB', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50016');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'IIE', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'Desarrollo', '10.33.141.253', '50016');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'ADMSEG', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAF', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'ING', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50000');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'MEDPREVD', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'LICENCIA', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAFINT', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50002');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIGTIC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50004');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SUAJ', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50006');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SIAFINP', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50010');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'CIS', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'DNC', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50012');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'TFADMSEG', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'TFCIS', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'TFLFD', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SITFYM', '', 'DB2', 'RedHat 5.7', 'Bajo', 3, 'QA', '10.38.10.8', '50016');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SUI_LFD', '', 'PostgreSQL', 'CentOS 7.7', 'Bajo', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'TIMBRADO SCT', '', 'PostgreSQL', 'CentOS 7.4', 'Bajo', 3, 'QA', '10.33.146.20', '5432');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'TIMBRADO AFAC', '', 'PostgreSQL', 'CentOS 7.4', 'Bajo', 3, 'QA', '10.38.10.20', '5432');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'JIRA', '', 'PostgreSQL', 'Ubuntu 18.04', 'Bajo', 3, 'QA', '10.38.239.37', '5432');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'GITLAB', '', 'PostgreSQL', 'RedHat 7.9', 'Bajo', 3, 'QA', '10.33.146.22', '5432');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'SUAJ', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.11.11', '5432');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'RECO', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5440');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'RNSAOP', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5440');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'ADMSEG_SVC', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5440');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'REGAUDIT', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5440');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'CABMUN', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5444');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'C_RURALES_BACK', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5444');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'C_RURALES_SEPOMEX', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5444');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'VUELA_SEGURO', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5446');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'CAT_RENAPO', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5448');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'RSIE', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5448');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'RSIPUMEX', '', 'PostgreSQL', 'RedHat 8.3', 'Bajo', 3, 'QA', '10.38.10.19', '5448');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'siarmx', '', 'MySQL', 'CentOS 6.3', 'Bajo', 3, 'QA', '10.38.241.28', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'cass', '', 'MySQL', 'CentOS 6.3', 'Bajo', 3, 'QA', '10.38.241.28', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'banco_digital', '', 'MySQL', 'CentOS 6.3', 'Bajo', 3, 'QA', '10.38.241.28', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'glpi_sct', '', 'MySQL', 'Ubuntu 18.04', 'Bajo', 3, 'QA', '10.38.239.36', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'joomla_db', '', 'MySQL', 'RedHat 8.6', 'Bajo', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'sfv_portal', '', 'MySQL', 'RedHat 8.4', 'Bajo', 3, 'QA', '10.38.239.39', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'sfv_acceso', '', 'MySQL', 'RedHat 8.4', 'Bajo', 3, 'QA', '10.38.239.39', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'sintqa_portal', '', 'MySQL', 'RedHat 8.4', 'Bajo', 3, 'QA', '10.38.241.25', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'pdn_portal', '', 'MySQL', 'RedHat 8.5', 'Bajo', 3, 'QA', '10.38.240.29', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'repo_portal', '', 'MySQL', 'RedHat 8.5', 'Bajo', 3, 'QA', '10.38.240.29', '3306');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'Pegasus', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'Pegasus_110821', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'Pegasus_Consulta', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'Pegasus_Contenido', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'Pegasus_Contenido_2', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'Pegasus_Contenido_6', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'Pegasus_SSIS', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'PegasusV10', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'Pegasusv8', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.3', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'Pegasus_clon', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'Pegasus_SSIS', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.12', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'ReportServer', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.12', '');
INSERT INTO `databases` (`id`, `name`, `short_name`, `dbms`, `so`, `criticality`, `level_id`, `enviroment`, `ip`, `port`) VALUES(NULL, 'ReportServerTempDB', '', 'SQL Server', 'Windows Server 2016', 'Medio', 3, 'QA', '10.38.10.12', '');
